### ISSUE TITLE
RollupError when deploying to Cloudflare

### ISSUE THREAD

**Issue by mendrinos** [mholt/PapaParse#1056]
```
11:23:00.516 [error] [nitro] RollupError: Expected ',', got 'undefined' in /opt/buildhome/repo/node_modules/papaparse/papaparse.js
11:23:00.516 
11:23:00.516 
11:23:00.516 50:     var URL = global.URL || global.webkitURL || null;
11:23:00.516 51:     var code = moduleFactory.toString();
11:23:00.516 52:     return Papa.BLOB_URL || (Papa.BLOB_URL = URL.createObjectURL(new Blob(["var global = (function() { if (typeof self !== 'undefined') { return self; } if ("undefined"...
11:23:00.517                                                                                                                                                                   ^
11:23:00.517 53:   }
11:23:00.518 [error] Expected ',', got 'undefined' in /opt/buildhome/repo/node_modules/papaparse/papaparse.js
11:23:00.518   at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:396:41)
11:23:00.519   at convertProgram (node_modules/rollup/dist/es/shared/parseAst.js:1060:26)
11:23:00.519   at parseAst (node_modules/rollup/dist/es/shared/parseAst.js:2204:12)
11:23:00.519   at tryParse (node_modules/@rollup/plugin-commonjs/dist/es/index.js:17:12)
11:23:00.519   at analyzeTopLevelStatements (node_modules/@rollup/plugin-commonjs/dist/es/index.js:37:15)
11:23:00.519   at Object.transformAndCheckExports (node_modules/@rollup/plugin-commonjs/dist/es/index.js:2090:68)
11:23:00.519   at Object.transform (node_modules/@rollup/plugin-commonjs/dist/es/index.js:2290:41)
11:23:00.519   at node_modules/rollup/dist/es/shared/node-entry.js:19774:40 
11:23:00.520 
11:23:00.520 [error] Expected ',', got 'undefined' in /opt/buildhome/repo/node_modules/papaparse/papaparse.js
11:23:00.632 Failed: Error while executing user command. Exited with error code: 1
11:23:00.643 Failed: build command exited with code: 1
11:23:02.223 Failed: error occurred while running build command
```

**Comment by brunopbarbosa** [comment]
Getting the same error on a nuxt 3 project running nuxt build.

**Comment by ThomasSimonsen20** [comment]
@brunopbarbosa I'm running into the same issue with Nuxt 3, did u find a solution?

**Comment by nsina** [comment]
> @brunopbarbosa I'm running into the same issue with Nuxt 3, did u find a solution?

You can try to bypass this issue for the affected component by wrapping it in `<ClientOnly>` so it only renders on client side.

**Comment by michaelreinhard1** [comment]
> [@brunopbarbosa](https://github.com/brunopbarbosa) I'm running into the same issue with Nuxt 3, did u find a solution?

I'm also having the same issue, did you find a solution?

> > [@brunopbarbosa](https://github.com/brunopbarbosa) I'm running into the same issue with Nuxt 3, did u find a solution?
> 
> You can try to bypass this issue for the affected component by wrapping it in `<ClientOnly>` so it only renders on client side.

Unfortunately wrapping it in `<ClientOnly>` did not work.

**Comment by brunopbarbosa** [comment]
> > [@brunopbarbosa](https://github.com/brunopbarbosa) I'm running into the same issue with Nuxt 3, did u find a solution?
> 
> I'm also having the same issue, did you find a solution?
> 
> > > [@brunopbarbosa](https://github.com/brunopbarbosa) I'm running into the same issue with Nuxt 3, did u find a solution?
> > 
> > 
> > You can try to bypass this issue for the affected component by wrapping it in `<ClientOnly>` so it only renders on client side.
> 
> Unfortunately wrapping it in `<ClientOnly>` did not work.

Hey, unfortunately I ended up getting rid of PapaParse entirely. I don't exactly remember anymore, but I think client Only also didn't work for me.

**Comment by michaelreinhard1** [comment]
> > > [@brunopbarbosa](https://github.com/brunopbarbosa) I'm running into the same issue with Nuxt 3, did u find a solution?
> > 
> > 
> > I'm also having the same issue, did you find a solution?
> > > > [@brunopbarbosa](https://github.com/brunopbarbosa) I'm running into the same issue with Nuxt 3, did u find a solution?
> > > 
> > > 
> > > You can try to bypass this issue for the affected component by wrapping it in `<ClientOnly>` so it only renders on client side.
> > 
> > 
> > Unfortunately wrapping it in `<ClientOnly>` did not work.
> 
> Hey, unfortunately I ended up getting rid of PapaParse entirely. I don't exactly remember anymore, but I think client Only also didn't work for me.

Hey, thanks for letting me know! I was thinking about doing the same, I'll also just get rid of it and use a different one! Thanks

**Comment by adorack** [comment]
This happens because Nuxt is built on Nitro, and Nitro configures Rollup to do a blind search-and-replace for the literal string `typeof window`, replacing it with the literal string `"undefined"`: https://github.com/nitrojs/nitro/blob/3b31e9d73386b01c6e1dd19ece9720819eeda4e4/src/rollup/config.ts#L254.  That in turn introduces a syntax error when trying to parse PapaParse's worker blob because the double quotes end up nested incorrectly: https://github.com/mholt/PapaParse/blob/e3c7b2628c68b868fd09862252eea312fbafdd84/papaparse.js#L52.

I'm not sure what the right solution here is... arguably, the bug is in Nitro.  They appear to be doing it for performance reasons (https://github.com/nitrojs/nitro/commit/fdb24215b0598d179d048a05d6ece3755d206847).

**Comment by adorack** [comment]
I filed a bug with Nitro: https://github.com/nitrojs/nitro/issues/3071.

I'm able to work around this issue by applying this config in Nuxt:

```
  nitro: {
    preset: 'cloudflare-module',
    replace: {
      'typeof window': '`undefined`',
    },
  },
```

**Comment by imgta** [comment]
> I filed a bug with Nitro: [nitrojs/nitro#3071](https://github.com/nitrojs/nitro/issues/3071).
> 
> I'm able to work around this issue by applying this config in Nuxt:
> 
> ```
>   nitro: {
>     preset: 'cloudflare-module',
>     replace: {
>       'typeof window': '`undefined`',
>     },
>   },
> ```

Appreciate the breakdown of this bug and the workaround! Using `cloudflare-pages` for the preset worked in my case.

**Comment by dboskovic** [comment]
Will address in the upcoming v6 release.
