### ISSUE TITLE
Worker error on JSFiddle

### ISSUE THREAD

**Issue by idibidiart** [mholt/PapaParse#455]
Trying 'worker: true' but getting this error 

Why aren't you constructing the worker dynamically ?  How is this supposed to work? I couldn't see anything in the docs from first glance. 

Uncaught DOMException: Failed to construct 'Worker': Script at 'https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.3.7/papaparse.min.js?papaworker' cannot be accessed from origin 'https://fiddle.jshell.net'.
    at k (https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.3.7/papaparse.min.js:7:13380)
    at Object.a [as parse] (https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.3.7/papaparse.min.js:7:327)

**Comment by pokoli** [comment]
@idibidiart #428 added suport for generatinc the worker dinamically, but it's still missing some changes in order to be merged. Does it fix the issue for you?
