### ISSUE TITLE
Error using transformHeader with header: true and worker: true

### ISSUE THREAD

**Issue by bleuf1sh** [mholt/PapaParse#761]
The error was about not being able to clone in postMessage.

I was working with a remote csv in a Chrome Web Front End.

**Comment by pokoli** [comment]
could you post the full tracebak?

**Comment by bleuf1sh** [comment]
I've provided the example function as well and removed private details.

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': (h) => {
                    return h.trim();
                } could not be cloned.
    at Object.parse (chrome-extension://asfdasdf/background/background.js:35623:967)
    at chrome-extension://asfdasdf/background/background.js:46081:18
    at new Promise (<anonymous>)
    at Function.loadCsvRules (chrome-extension://asfdasdf/background/background.js:46079:16)
```

```

private static async loadCsvRules(csvUrl: string): Promise<any[]> {
    return new Promise( (resolve, reject) => {
      const datas = [];
      Papa.parse(csvUrl, {
        download: true,
        header: true,
        worker: true,
        transformHeader: (h) => {
          return h.trim();
        },
        step: (row) => {
          datas.push(row.data);
        },
        complete: () => {
          resolve(datas);
        }
      });
    });
  }

```

**Comment by abodnar** [comment]
I'm having this same problem as well. Any suggestions on how to resolve this?

**Comment by steveryan** [comment]
Having the same issue over here. Would love to find a workaround for this.

**Comment by ux-engineer** [comment]
Same here...

**Comment by jchan18** [comment]
Is there any update with this issue? I'm seeing this problem too

**Comment by mikeappell** [comment]
👍 on this, it seems like `transformHeader` is incompatible with `worker: true` which really stinks. Even
```transformHeader: header => header```
seems like it fails; assuming the function is being passed to the worker and simply cannot be serialized.

Just so as not to poo all over an amazing project: PapaParse is really excellent and has proven utterly invaluable, so thanks for such an awesome tool 🎊

**Comment by jaymathew** [comment]
I'm a new PapaParse user, and I wish this were fixed or documented. It would have saved me some time.  The last message was over a year ago, and I hate to beat a dead horse, but is there any update on this issue?

**Comment by joaquinricci** [comment]
Same thing happen to me but with `transform` and not `transformHeader`.

**Comment by m1m1s1ku** [comment]
Same issue in 2025

**Comment by Tremorok** [comment]
same issue in 2026
